//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectNatillera.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class AlquileresLugar
    {
        public int CodigoAlquiler { get; set; }
        public int CodigoLugar { get; set; }
        public Nullable<int> CodigoEvento { get; set; }
        public System.DateTime FechaInicioAlquiler { get; set; }
        public System.DateTime FechaFinAlquiler { get; set; }
        public decimal CostoTotalAlquiler { get; set; }
        public string EstadoAlquiler { get; set; }

        [JsonIgnore]    
        public virtual Lugare Lugare { get; set; }
        [JsonIgnore]
        public virtual Evento Evento { get; set; }
    }
}
