//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectNatillera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactosProveedor
    {
        public int CodigoContacto { get; set; }
        public string DocumentoProveedor { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
    
        public virtual Proveedore Proveedore { get; set; }
    }
}
