//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectNatillera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentasAhorro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentasAhorro()
        {
            this.TransaccionesAhorroes = new HashSet<TransaccionesAhorro>();
        }
    
        public int CodigoCuenta { get; set; }
        public string DocumentoCliente { get; set; }
        public string NumeroCuenta { get; set; }
        public int CodigoTipoCuenta { get; set; }
        public System.DateTime FechaApertura { get; set; }
        public decimal Saldo { get; set; }
        public string Estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual TiposCuentaAhorro TiposCuentaAhorro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransaccionesAhorro> TransaccionesAhorroes { get; set; }
    }
}
