//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectNatillera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentosCliente
    {
        public int CodigoDocumento { get; set; }
        public string DocumentoCliente { get; set; }
        public int CodigoTipoDocumento { get; set; }
        public string NombreArchivo { get; set; }
        public System.DateTime FechaCarga { get; set; }
        public bool Vigente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual TiposDocumentoLegal TiposDocumentoLegal { get; set; }
    }
}
