//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectNatillera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evento()
        {
            this.AlquileresLugars = new HashSet<AlquileresLugar>();
            this.EventosProveedores = new HashSet<EventosProveedore>();
            this.GastosEventoes = new HashSet<GastosEvento>();
            this.ParticipacionEventos = new HashSet<ParticipacionEvento>();
        }
    
        public int CodigoEvento { get; set; }
        public string NombreEvento { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public Nullable<int> CodigoLugar { get; set; }
        public Nullable<decimal> PresupuestoEstimado { get; set; }
        public string EstadoEvento { get; set; }
        public string DocumentoOrganizadorCliente { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlquileresLugar> AlquileresLugars { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Lugare Lugare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventosProveedore> EventosProveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GastosEvento> GastosEventoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipacionEvento> ParticipacionEventos { get; set; }
    }
}
