//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectNatillera.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Liquidacione
    {
        public int CodigoLiquidacion { get; set; }
        public string DocumentoCliente { get; set; }
        public System.DateTime FechaLiquidacion { get; set; }
        public Nullable<decimal> ValorTotalAhorros { get; set; }
        public Nullable<decimal> ValorTotalPrestamosPendientes { get; set; }
        public Nullable<decimal> MontoFinalLiquidacion { get; set; }
        public string EstadoLiquidacion { get; set; }

        [JsonIgnore]
        public virtual Cliente Cliente { get; set; }
    }
}
