//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectNatillera.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NatilleraDBEntities : DbContext
    {
        public NatilleraDBEntities()
            : base("name=NatilleraDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlquileresLugar> AlquileresLugars { get; set; }
        public virtual DbSet<Ciudade> Ciudades { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<ContactosProveedor> ContactosProveedors { get; set; }
        public virtual DbSet<CuentasAhorro> CuentasAhorroes { get; set; }
        public virtual DbSet<Departamento> Departamentos { get; set; }
        public virtual DbSet<DocumentosCliente> DocumentosClientes { get; set; }
        public virtual DbSet<Evento> Eventos { get; set; }
        public virtual DbSet<EventosProveedore> EventosProveedores { get; set; }
        public virtual DbSet<GastosEvento> GastosEventoes { get; set; }
        public virtual DbSet<Liquidacione> Liquidaciones { get; set; }
        public virtual DbSet<Lugare> Lugares { get; set; }
        public virtual DbSet<MetodosPago> MetodosPagoes { get; set; }
        public virtual DbSet<PagosPrestamo> PagosPrestamoes { get; set; }
        public virtual DbSet<Pais> Paises { get; set; }
        public virtual DbSet<ParticipacionEvento> ParticipacionEventos { get; set; }
        public virtual DbSet<Prestamo> Prestamos { get; set; }
        public virtual DbSet<Proveedore> Proveedores { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TiposCuentaAhorro> TiposCuentaAhorroes { get; set; }
        public virtual DbSet<TiposDocumentoLegal> TiposDocumentoLegals { get; set; }
        public virtual DbSet<TiposServicioProveedor> TiposServicioProveedors { get; set; }
        public virtual DbSet<TiposTransaccion> TiposTransaccions { get; set; }
        public virtual DbSet<TransaccionesAhorro> TransaccionesAhorroes { get; set; }
        public virtual DbSet<UsuariosSistema> UsuariosSistemas { get; set; }
    }
}
