//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectNatillera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagosPrestamo
    {
        public int CodigoPago { get; set; }
        public int CodigoPrestamo { get; set; }
        public decimal MontoPago { get; set; }
        public System.DateTime FechaPago { get; set; }
        public Nullable<decimal> CapitalPagado { get; set; }
        public Nullable<decimal> InteresesPagados { get; set; }
        public Nullable<decimal> MultasPagadas { get; set; }
        public Nullable<decimal> SaldoPendiente { get; set; }
    
        public virtual Prestamo Prestamo { get; set; }
    }
}
