//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectNatillera.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipacionEvento
    {
        public int CodigoParticipacion { get; set; }
        public int CodigoEvento { get; set; }
        public string DocumentoCliente { get; set; }
        public System.DateTime FechaInscripcion { get; set; }
        public Nullable<decimal> MontoPagadoInscripcion { get; set; }
        public string EstadoParticipacion { get; set; }

        [JsonIgnore]
        public virtual Cliente Cliente { get; set; }
        [JsonIgnore]
        public virtual Evento Evento { get; set; }
    }
}
