//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectNatillera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prestamo()
        {
            this.PagosPrestamoes = new HashSet<PagosPrestamo>();
        }
    
        public int CodigoPrestamo { get; set; }
        public string DocumentoCliente { get; set; }
        public decimal MontoSolicitado { get; set; }
        public Nullable<decimal> MontoAprobado { get; set; }
        public decimal TasaInteres { get; set; }
        public int PlazoMeses { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public Nullable<System.DateTime> FechaDesembolso { get; set; }
        public string EstadoPrestamo { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagosPrestamo> PagosPrestamoes { get; set; }
    }
}
