//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectNatillera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransaccionesAhorro
    {
        public int CodigoTransaccion { get; set; }
        public int CodigoCuenta { get; set; }
        public int CodigoTipoTransaccion { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime FechaTransaccion { get; set; }
        public Nullable<decimal> SaldoAnterior { get; set; }
        public Nullable<decimal> SaldoPosterior { get; set; }
    
        public virtual CuentasAhorro CuentasAhorro { get; set; }
        public virtual TiposTransaccion TiposTransaccion { get; set; }
    }
}
