//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectNatillera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosSistema
    {
        public int CodigoUsuario { get; set; }
        public string DocumentoCliente { get; set; }
        public string NombreUsuario { get; set; }
        public string ClaveHash { get; set; }
        public string Salt { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public bool Activo { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
